### ISSUE TITLE
User story

### ISSUE THREAD

**Issue by krutarth4** [krutarth4/SHYFTX#7]
Create some user story to see how it works for customer or stakeholder in normal day to day life

**Comment by vahidjb** [comment]
For Farmers/Brokers (Senders)
1. Registration and Profile Setup
User Story: As a farmer/broker, I want to create a profile with my business information, so that I can start using the logistics platform.

Acceptance Criteria:
- Collect business details, contact information, and produce types.
- Allow users to set preferences for shipping frequency and preferred booking times.

2. Price Model Setup
User Story: As a farmer/broker, I want to see the price per kilometer when I request a rider, so that I can make informed decisions about the cost of transport.

Acceptance Criteria:
- Display rider's price per kilometer
- Show a summary of the estimated total cost before confirming the order.

3. Suggestion and Filtering
User Story: As a farmer/broker, I want to see prioritized suggestions for truck owners based on my needs, so that I can quickly find suitable transport options.
Acceptance Criteria:

- Present a list of truck owners with filters such as proximity, price, and vehicle capacity.
- Allow sorting and filtering of results based on preferences.

4. Order Request and Matching System
User Story: As a farmer/broker, I want to submit a transport request and have the system match my order with other nearby orders, so that I can reduce transportation costs.
Acceptance Criteria:

- Allow submission of detailed transport requests.
- Display potential cost savings and route details if the order is pooled with others.
- Allow users to accept or decline the pooled transport option.

5. Incentive System
User Story: As a farmer, I want to receive vouchers for accepting pooled transport offers, so that I am encouraged to use this cost-saving option.
Acceptance Criteria:

- Provide a clear explanation of the voucher system when a pooling option is presented.
- Issue vouchers automatically upon acceptance of a pooling offer and confirm via email/SMS.

6. Payment Options
User Story: As a farmer/broker, I want to choose between online or cash payment options, so that I have flexibility in how I pay for transport services.
Acceptance Criteria:

- Provide an option to select the payment method during the order request process.
- Offer secure online payment processing and confirmation of cash payment instructions.
- Payment could be held in SHYFTX's account until delivery confirmation, ensuring reliability and trust.

7. Order Management System
User Story: As a farmer/broker, I want to track the progress of ongoing orders and access archived orders, so that I can manage my shipments effectively.
Acceptance Criteria:

- Provide a dashboard to track ongoing orders with status updates (e.g., accepted, preparing for pickup, in transit, delivered).
- Allow access to archived orders for reference and record-keeping.
- Send notifications via email and SMS for order acceptance, rejection, preparation for pickup, and delivery confirmation.

8. Notifications for Order Status
User Story: As a farmer/broker, I want to receive notifications by email and SMS when my order is accepted or rejected, is being prepared for pickup, and when it is delivered, so that I stay informed about the status of my shipments.
Acceptance Criteria:

- Send confirmation notifications via email and SMS upon order acceptance and rejection.
- Notify users when it is time to prepare for pickup.
- Confirm delivery completion through email and SMS notifications.

9. Contract Agreement
User Story: As a farmer/broker, I want to sign a standard contract agreement with truck owners, so that I can ensure clarity and compliance with legal requirements.
Acceptance Criteria:

- Provide a standard contract template during the registration process.
- Ensure both parties sign the contract before commencing services.


For Riders (Truck Owners)
1. Registration and KYC
User Story: As a rider, I want to complete a registration process that includes KYC and vehicle information, so that I can start receiving transport orders.
Acceptance Criteria:

- Collect and verify personal identification and vehicle information during registration.
- Allow riders to set their price per kilometer during the registration process.

2. Order Notifications
User Story: As a rider, I want to receive notifications about new orders via the app and SMS, so that I can quickly decide whether to accept or cancel them.
Acceptance Criteria:

- Send real-time notifications for new orders through the app and SMS.
- Provide details about the order, including pickup location, destination, and price.

3. Order Acceptance and Management
User Story: As a rider, I want to access load details and status updates for my orders, so that I can manage my transport efficiently.
Acceptance Criteria:

- Allow riders to accept or cancel orders through the app.
- Provide access to load details, pickup date, and status updates for each order.
- Include navigation links to optimized routes for single or batched orders.

4. Order Management System
User Story: As a rider, I want to track the progress of ongoing orders and access archived orders, so that I can manage my deliveries effectively.
Acceptance Criteria:

- Provide a dashboard to track ongoing orders with status updates (e.g., accepted, preparing for pickup, in transit, delivered).
- Allow riders to access archived orders for reference and record-keeping.
- Send notifications via email and SMS for order acceptance, rejection, preparation for pickup, and delivery confirmation.

5. Notifications for Order Status
User Story: As a rider, I want to receive notifications by email and SMS when I accept or reject an order, prepare for pickup, and deliver the order, so that I stay informed about my tasks.
Acceptance Criteria:

- Send confirmation notifications via email and SMS upon order acceptance and rejection.
- Notify riders when it is time to prepare for pickup.
- Confirm delivery completion through email and SMS notifications.

6. Contract Agreement
User Story: As a rider, I want to sign a standard contract agreement with farmers/brokers, so that I can ensure clarity and compliance with legal requirements.
Acceptance Criteria:

- Provide a standard contract template during the registration process.
- Ensure both parties sign the contract before commencing services.

**Comment by vahidjb** [comment]
User stories updated. We should talk and decide which ones exactly going to present
@krutarth4

**Comment by krutarth4** [comment]
> User stories updated. We should talk and decide which ones exactly going to present [@krutarth4](https://github.com/krutarth4)

you mean which one to select for the presentation(final pitch )?

**Comment by vahidjb** [comment]
Yep!

**Comment by krutarth4** [comment]
Trucks category 

Transporting goods requires different types of trucks, each designed to handle specific types of cargo. Here are some common types of trucks and their specifications:

    Flatbed Trucks:
        Description: These trucks have a flat, open bed with no sides or roof.
        Usage: Ideal for transporting oversized or irregularly shaped cargo, construction materials, and heavy machinery.
        Specifications: Usually, no temperature control; focus on load securing mechanisms.

    Box Trucks (Dry Vans):
        Description: Enclosed rectangular cargo area, often used for moving goods locally.
        Usage: Common for transporting furniture, non-perishable goods, and appliances.
        Specifications: Standardized sizes, no temperature control, weather protection.

    Refrigerated Trucks (Reefers):
        Description: Insulated and equipped with a refrigeration unit.
        Usage: Transport perishable goods like food, pharmaceuticals, and flowers.
        Specifications: Temperature control from below freezing to ambient, humidity control, data logging for temperature monitoring.

    Tanker Trucks:
        Description: Cylindrical tank designed to carry liquids or gases.
        Usage: Transporting fuel, chemicals, milk, and other liquids.
        Specifications: Often have compartments, temperature control for certain liquids, special coatings for corrosion resistance.

    Flatbed with Conestoga:
        Description: Flatbed with a retractable tarping system.
        Usage: Provides the flexibility of a flatbed with the protection of a dry van.
        Specifications: No temperature control, ease of loading/unloading, weather protection.

    Dump Trucks:
        Description: Open-box bed hinged at the rear, hydraulic pistons lift the front.
        Usage: Transporting loose materials like sand, gravel, or demolition waste.
        Specifications: No temperature control, heavy-duty construction, specific weight limits.

    Livestock Trucks:
        Description: Designed to transport live animals.
        Usage: Moving cattle, sheep, pigs, and other livestock.
        Specifications: Ventilation systems, non-slip flooring, partitions for animal separation, sometimes temperature control.

    Curtainside Trucks:
        Description: Sides covered by a tarpaulin, can be opened for loading/unloading.
        Usage: Versatile for various types of cargo needing side loading.
        Specifications: No temperature control, flexibility for loading/unloading, weather protection.

    Lowboy Trailers:
        Description: Very low deck height.
        Usage: Transporting heavy equipment and machinery.
        Specifications: No temperature control, low center of gravity for stability, various deck lengths.

    Car Carrier Trucks:
        Description: Multi-level carriers designed for transporting cars.
        Usage: Delivering new and used vehicles.
        Specifications: No temperature control, loading ramps, multiple vehicle capacities.

    Side-lifter Trucks:
        Description: Equipped with cranes or lifts on the sides.
        Usage: Loading and unloading shipping containers without additional equipment.
        Specifications: No temperature control, hydraulic systems for lifting, container locks.

    Hopper Trucks:
        Description: Funnel-shaped containers for transporting bulk dry goods.
        Usage: Grain, coal, sand, and similar materials.
        Specifications: No temperature control, gravity unloading, various capacities.

    Box Trucks with Liftgate:
        Description: Enclosed cargo area with a hydraulic lift at the rear.
        Usage: Easier loading/unloading of heavy items, especially without loading docks.
        Specifications: Lift capacity specifications, no temperature control, standard box truck features.

    Dry Bulk Trucks:
        Description: Enclosed tanks for dry bulk materials.
        Usage: Transporting powdered cement, flour, plastic pellets.
        Specifications: No temperature control, pressurized unloading systems, specific material handling designs.
